version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
      - searxng
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'ENABLE_WEB_SEARCH=True'
      - 'SEARXNG_URL=http://searxng:8080'
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    environment:
      - "HSA_OVERRIDE_GFX_VERSION=gfx1030"
      - "OLLAMA_DEBUG=1"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
  
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8888:8080"
    volumes:
      - searxng_data:/etc/searxng
    environment:
      - "SEARXNG_BASE_URL=http://localhost:8888/"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  open-webui: {}
  ollama_data: {}
  searxng_data: {}
  portainer_data: {}
