# Docker Compose file for Open WebUI, Ollama, and Portainer
# Version specifies the file format. '3.8' is a recent, stable version.
version: '3.8'

services:
  # Defines the Open WebUI service
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    # Depends on the ollama service to ensure it starts first.
    depends_on:
      - ollama
    ports:
      # Exposes Open WebUI on port 3000 of the host machine.
      - "3000:8080"
    environment:
      # Explicitly tells Open WebUI where to find the Ollama API.
      # 'ollama' is the service name of the Ollama container.
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

  # Defines the Ollama service, translated from your 'docker run' command.
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    environment:
      - "HSA_OVERRIDE_GFX_VERSION=gfx1030"
      - "OLLAMA_DEBUG=1"
    # Maps host GPU devices to the container for hardware acceleration.
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      # Using a named volume to persist Ollama models and data.
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  # Defines the Portainer service for Docker management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

# Defines the named volumes used by the services for persistent data.
volumes:
  open-webui: {}
  ollama_data: {}
  portainer_data: {}
