# Docker Compose file for Open WebUI and Portainer
# Version specifies the file format. '3.8' is a recent, stable version.
version: '3.8'

services:
  # Defines the Open WebUI service
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    # Use host networking to allow the container to directly access
    # services running on the host machine, like Ollama.
    network_mode: "host"
    volumes:
      - open-webui:/app/backend/data
    environment:
      # Sets the internal port for the Open WebUI application.
      # Since we are using host networking, this is the port that will be used on the host.
      - 'PORT=3001'
    # When using 'network_mode: "host"', the container's port is exposed directly on the host.
    # Open WebUI will now be accessible on the port defined above: http://localhost:3001
    restart: unless-stopped

  # Defines the Portainer service for Docker management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      # Portainer UI will be available on port 9443 (HTTPS)
      - "9443:9443"
      # Port 8000 is used for the tunnel server (optional but recommended)
      - "8000:8000"
    volumes:
      # Mounts the Docker socket to allow Portainer to manage Docker itself.
      - /var/run/docker.sock:/var/run/docker.sock
      # Persists Portainer's configuration data.
      - portainer_data:/data
    restart: always

# Defines the named volumes used by the services.
volumes:
  open-webui: {}
  portainer_data: {}
